In [31]:
import os
import sys

project_root = os.path.abspath("..")
sys.path.append(project_root)

In [32]:
from backend.ai.rag_pipeline import get_rag_response

In [33]:
question = "How can I reset my password?"

response = get_rag_response(question)

print(response)

Toreset your password, follow these steps:

1. Go to the login page of the service or app.
2. Click the **“Forgot password?”** or **“Reset password”** link (usually near the password field).
3. Enter the email address associated with your account and submit the request.
4. Check your email inbox (and spam/junk folder) for a password‑reset message.
5. Click the reset link in the email and follow the prompts to create a new password.
6. Log in with your new password.

If you don’t receive the email or encounter any issues, please let me know the specific platform you’re trying to access, and I can provide more detailed instructions or escalate the request to support.

In [34]:
import pandas as pd

test_data = pd.read_csv("../data/evaluation/test_dataset.csv")

test_data

,question,ground_truth
0,How can I reset my password?,"To reset your password, click 'Forgot Password..."
1,How do I cancel my order?,You can cancel your order before it is shipped...
2,How can I request a refund?,You can request a refund by contacting custome...
3,How do I track my order?,You can track your order using the tracking nu...
4,How do I change my email address?,Go to Account Settings and update your email a...
5,How can I contact customer support?,You can contact customer support through live ...
6,What payment methods do you accept?,"We accept credit cards, debit cards, and PayPal."
7,How long does shipping take?,Shipping usually takes between 3 and 7 busines...
8,Can I change my delivery address?,You can change your delivery address before yo...
9,How do I update my account information?,Go to your profile settings and update your pe...
10,How do I create a new account?,You can create a new account by clicking Sign ...
11,Why was my payment declined?,Your payment may have been declined due to inc...
12,How do I add a new payment method?,You can add a new payment method from the Paym...
13,Can I use a discount code?,You can apply a discount code during checkout ...
14,Where can I find my order history?,Your order history is available in the Orders ...
15,How do I return a product?,You can return a product by submitting a retur...
16,What is your return policy?,Our return policy allows customers to return e...
17,How do I know if my order was successful?,You will receive a confirmation email after yo...
18,Can I place an order without an account?,"Yes, you can place an order as a guest if gues..."
19,How do I change my password?,You can change your password from the Security...
20,How do I delete my account?,You can request account deletion by contacting...
21,Why is my order delayed?,Orders may be delayed due to shipping issues o...
22,How can I check product availability?,You can check product availability on the prod...
23,Do you offer international shipping?,"Yes, international shipping is available for s..."
24,How can I subscribe to notifications?,You can subscribe to notifications from your a...
25,How do I unsubscribe from emails?,You can unsubscribe using the link at the bott...
26,What should I do if I forgot my username?,You can recover your username by contacting cu...
27,How do I verify my account?,You can verify your account by following the v...
28,Can I order multiple products together?,"Yes, you can add multiple products to your car..."
29,How do I apply for a warranty?,You can apply for warranty service by contacti...
30,How long is the warranty period?,The warranty period depends on the product and...
31,Can I exchange my product?,You can request an exchange by submitting an e...
32,What happens if I receive a damaged product?,Contact customer support and provide details a...
33,How do I update my phone number?,You can update your phone number from your Acc...
34,How do I check my shipping status?,You can check shipping status using your order...
35,Can I save items for later?,You can save items by adding them to your wish...
36,How do I remove items from my cart?,You can remove items by opening your cart and ...
37,Why did I receive the wrong item?,Contact customer support to report receiving t...
38,How do I download my invoice?,You can download your invoice from the Orders ...
39,Are there any shipping fees?,Shipping fees depend on your location and orde...
40,How can I change my notification settings?,You can change notification settings from your...
41,What if my package never arrives?,Contact customer support if your package does ...
42,Can I pay using cash on delivery?,Cash on delivery is available in selected loca...
43,How do I apply for a refund?,Submit a refund request through your account o...
44,How do I report a problem with my order?,You can report order problems by contacting cu...
45,How do I know my personal data is safe?,We protect your personal data using security m...
46,How can I update my billing information?,You can update billing information from the pa...
47,How do I find a product?,You can search for products using the search b...
48,How do I create a wishlist?,You can create a wishlist by clicking the Add ...
49,How can I contact support about a technical is...,You can contact technical support through emai...

In [35]:
predictions = []

for question in test_data["question"]:
    answer = get_rag_response(question)
    predictions.append(answer)

test_data["prediction"] = predictions

test_data

WARNING:backend.ai.rag_pipeline:Retryable error (attempt 1/3), waiting 10s: {'message': 'Upstream error from Nvidia: ResourceExhausted: Worker local total request limit reached (1062/32)', 'code': 502}
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 1/3), waiting 10s: {'message': 'Upstream error from Nvidia: ResourceExhausted: Worker local total request limit reached (159/32)', 'code': 502}
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 1/3), waiting 10s: {'message': 'Upstream error from Nvidia: ResourceExhausted: Worker local total request limit reached (32/32)', 'code': 502}
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 1/3), waiting 10s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 2/3), waiting 20s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Rate limited after 3 attempts
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 1/3), waiting 10s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 2/3), waiting 20s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Rate limited after 3 attempts
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 1/3), waiting 10s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 2/3), waiting 20s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Rate limited after 3 attempts
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 1/3), waiting 10s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 2/3), waiting 20s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Rate limited after 3 attempts
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 1/3), waiting 10s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 2/3), waiting 20s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Rate limited after 3 attempts
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 1/3), waiting 10s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 2/3), waiting 20s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Rate limited after 3 attempts
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 1/3), waiting 10s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Retryable error (attempt 2/3), waiting 20s: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1783468800000'}, 'provider_name': None}}, 'user_id': 'user_3GAZb3z8XdpZXJ0h1KGY1YOnxee'}
WARNING:backend.ai.rag_pipeline:Rate limited after 3 attempts

,question,ground_truth,prediction
0,How can I reset my password?,"To reset your password, click 'Forgot Password...","Toreset your password, follow these steps:\n\n..."
1,How do I cancel my order?,You can cancel your order before it is shipped...,"To cancel your order, please follow these gene..."
2,How can I request a refund?,You can request a refund by contacting custome...,"Okay, the user is asking how to request a refu..."
3,How do I track my order?,You can track your order using the tracking nu...,"To track your order, you'll typically need you..."
4,How do I change my email address?,Go to Account Settings and update your email a...,1. Log in to your account on the website or ap...
5,How can I contact customer support?,You can contact customer support through live ...,You can typically contact customer support thr...
6,What payment methods do you accept?,"We accept credit cards, debit cards, and PayPal.",We accept the following payment methods:\n\n- ...
7,How long does shipping take?,Shipping usually takes between 3 and 7 busines...,Shipping times vary depending on your location...
8,Can I change my delivery address?,You can change your delivery address before yo...,"Yes, you can often change your delivery addres..."
9,How do I update my account information?,Go to your profile settings and update your pe...,Here are the general steps to update your acco...
10,How do I create a new account?,You can create a new account by clicking Sign ...,Here are the general steps to create a new acc...
11,Why was my payment declined?,Your payment may have been declined due to inc...,I'm sorry to hear your payment was declined. W...
12,How do I add a new payment method?,You can add a new payment method from the Paym...,"Toadd a new payment method, follow these gener..."
13,Can I use a discount code?,You can apply a discount code during checkout ...,"Yes, you can typically use a discount code dur..."
14,Where can I find my order history?,Your order history is available in the Orders ...,You can typically find your order history by l...
15,How do I return a product?,You can return a product by submitting a retur...,"To return a product, follow these general step..."
16,What is your return policy?,Our return policy allows customers to return e...,I don't have access to the specific return pol...
17,How do I know if my order was successful?,You will receive a confirmation email after yo...,"To confirm if your order was successful, check..."
18,Can I place an order without an account?,"Yes, you can place an order as a guest if gues...","Yes, you can place an order without creating a..."
19,How do I change my password?,You can change your password from the Security...,Here are the general steps to change your pass...
20,How do I delete my account?,You can request account deletion by contacting...,"Okay, the user is asking how to delete their a..."
21,Why is my order delayed?,Orders may be delayed due to shipping issues o...,I'd be happy to help you check on your order d...
22,How can I check product availability?,You can check product availability on the prod...,Youcan typically check product availability us...
23,Do you offer international shipping?,"Yes, international shipping is available for s...","Yes, we ship internationally to most countries..."
24,How can I subscribe to notifications?,You can subscribe to notifications from your a...,To subscribe to notifications (such as order u...
25,How do I unsubscribe from emails?,You can unsubscribe using the link at the bott...,"To unsubscribe from marketing emails, follow t..."
26,What should I do if I forgot my username?,You can recover your username by contacting cu...,Here are the general steps to recover a forgot...
27,How do I verify my account?,You can verify your account by following the v...,"To verify your account, follow these general s..."
28,Can I order multiple products together?,"Yes, you can add multiple products to your car...","Yes, you can order multiple products in a sing..."
29,How do I apply for a warranty?,You can apply for warranty service by contacti...,SinceI don't have access to your specific comp...
30,How long is the warranty period?,The warranty period depends on the product and...,Warranty periods vary depending on the specifi...
31,Can I exchange my product?,You can request an exchange by submitting an e...,"Okay, the user is<unk><unk><unk><unk><unk><unk..."
32,What happens if I receive a damaged product?,Contact customer support and provide details a...,"Ifyou receive a damaged product, here’s what t..."
33,How do I update my phone number?,You can update your phone number from your Acc...,"Toupdate your phone number, follow these steps..."
34,How do I check my shipping status?,You can check shipping status using your order...,You can typically check your shipping status u...
35,Can I save items for later?,You can save items by adding them to your wish...,"Yes, you can typically save items for later us..."
36,How do I remove items from my cart?,You can remove items by opening your cart and ...,1. Open your shopping cart (usually via the ca...
37,Why did I receive the wrong item?,Contact customer support to report receiving t...,To help resolve the issue of receiving the wro...
38,How do I download my invoice?,You can download your invoice from the Orders ...,"To download your invoice, follow these steps:\..."
39,Are there any shipping fees?,Shipping fees depend on your location and orde...,"Shipping fees can vary based on a few factors,..."
40,How can I change my notification settings?,You can change notification settings from your...,Youcan adjust your notification preferences fr...
41,What if my package never arrives?,Contact customer support if your package does ...,"Ifyour package hasn't arrived, follow these st..."
42,Can I pay using cash on delivery?,Cash on delivery is available in selected loca...,"Okay, the user is<unk><unk><unk><unk><unk><unk..."
43,How do I apply for a refund?,Submit a refund request through your account o...,The service is busy right now. Please try agai...
44,How do I report a problem with my order?,You can report order problems by contacting cu...,The service is busy right now. Please try agai...
45,How do I know my personal data is safe?,We protect your personal data using security m...,The service is busy right now. Please try agai...
46,How can I update my billing information?,You can update billing information from the pa...,The service is busy right now. Please try agai...
47,How do I find a product?,You can search for products using the search b...,The service is busy right now. Please try agai...
48,How do I create a wishlist?,You can create a wishlist by clicking the Add ...,The service is busy right now. Please try agai...
49,How can I contact support about a technical is...,You can contact technical support through emai...,The service is busy right now. Please try agai...

In [44]:
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

smooth = SmoothingFunction().method1

bleu_scores = []

for _, row in test_data.iterrows():
    score = sentence_bleu(
        [row["ground_truth"].split()],
        row["prediction"].split(),
        smoothing_function=smooth
    )

    bleu_scores.append(score)

test_data["BLEU"] = bleu_scores

print("Average BLEU:", sum(bleu_scores) / len(bleu_scores))

Average BLEU: 0.007041957930289638

In [45]:
from rouge_score import rouge_scorer

scorer = rouge_scorer.RougeScorer(
    ["rouge1", "rouge2", "rougeL"],
    use_stemmer=True
)

rouge1 = []
rouge2 = []
rougeL = []

for _, row in test_data.iterrows():

    scores = scorer.score(
        row["ground_truth"],
        row["prediction"]
    )

    rouge1.append(scores["rouge1"].fmeasure)
    rouge2.append(scores["rouge2"].fmeasure)
    rougeL.append(scores["rougeL"].fmeasure)

test_data["ROUGE-1"] = rouge1
test_data["ROUGE-2"] = rouge2
test_data["ROUGE-L"] = rougeL

print("Average ROUGE-1:", sum(rouge1)/len(rouge1))
print("Average ROUGE-2:", sum(rouge2)/len(rouge2))
print("Average ROUGE-L:", sum(rougeL)/len(rougeL))

Average ROUGE-1: 0.1112873183779935
Average ROUGE-2: 0.03912004979266917
Average ROUGE-L: 0.08947836126115082

In [46]:
test_data

,question,ground_truth,prediction,BLEU,ROUGE-1,ROUGE-2,ROUGE-L
0,How can I reset my password?,"To reset your password, click 'Forgot Password...","Toreset your password, follow these steps:\n\n...",0.016264,0.220472,0.096000,0.157480
1,How do I cancel my order?,You can cancel your order before it is shipped...,"To cancel your order, please follow these gene...",0.006406,0.157895,0.053571,0.122807
2,How can I request a refund?,You can request a refund by contacting custome...,"Okay, the user is asking how to request a refu...",0.001035,0.030197,0.011641,0.025552
3,How do I track my order?,You can track your order using the tracking nu...,"To track your order, you'll typically need you...",0.008055,0.203704,0.075472,0.148148
4,How do I change my email address?,Go to Account Settings and update your email a...,1. Log in to your account on the website or ap...,0.005487,0.139130,0.070796,0.139130
5,How can I contact customer support?,You can contact customer support through live ...,You can typically contact customer support thr...,0.020339,0.111111,0.056338,0.111111
6,What payment methods do you accept?,"We accept credit cards, debit cards, and PayPal.",We accept the following payment methods:\n\n- ...,0.009570,0.301887,0.078431,0.188679
7,How long does shipping take?,Shipping usually takes between 3 and 7 busines...,Shipping times vary depending on your location...,0.002218,0.050847,0.000000,0.033898
8,Can I change my delivery address?,You can change your delivery address before yo...,"Yes, you can often change your delivery addres...",0.016838,0.204545,0.116279,0.204545
9,How do I update my account information?,Go to your profile settings and update your pe...,Here are the general steps to update your acco...,0.004786,0.132353,0.044776,0.088235
10,How do I create a new account?,You can create a new account by clicking Sign ...,Here are the general steps to create a new acc...,0.021314,0.180556,0.070423,0.152778
11,Why was my payment declined?,Your payment may have been declined due to inc...,I'm sorry to hear your payment was declined. W...,0.001948,0.116883,0.026316,0.090909
12,How do I add a new payment method?,You can add a new payment method from the Paym...,"Toadd a new payment method, follow these gener...",0.009647,0.157480,0.064000,0.110236
13,Can I use a discount code?,You can apply a discount code during checkout ...,"Yes, you can typically use a discount code dur...",0.022577,0.162602,0.099174,0.146341
14,Where can I find my order history?,Your order history is available in the Orders ...,You can typically find your order history by l...,0.005577,0.122449,0.055172,0.108844
15,How do I return a product?,You can return a product by submitting a retur...,"To return a product, follow these general step...",0.002423,0.067925,0.022814,0.052830
16,What is your return policy?,Our return policy allows customers to return e...,I don't have access to the specific return pol...,0.004204,0.128000,0.032520,0.112000
17,How do I know if my order was successful?,You will receive a confirmation email after yo...,"To confirm if your order was successful, check...",0.002576,0.069498,0.015564,0.069498
18,Can I place an order without an account?,"Yes, you can place an order as a guest if gues...","Yes, you can place an order without creating a...",0.042860,0.163265,0.082759,0.149660
19,How do I change my password?,You can change your password from the Security...,Here are the general steps to change your pass...,0.007192,0.092715,0.026846,0.066225
20,How do I delete my account?,You can request account deletion by contacting...,"Okay, the user is asking how to delete their a...",0.000591,0.020666,0.004603,0.016073
21,Why is my order delayed?,Orders may be delayed due to shipping issues o...,I'd be happy to help you check on your order d...,0.002634,0.152381,0.000000,0.095238
22,How can I check product availability?,You can check product availability on the prod...,Youcan typically check product availability us...,0.009547,0.129032,0.065359,0.090323
23,Do you offer international shipping?,"Yes, international shipping is available for s...","Yes, we ship internationally to most countries...",0.001791,0.076923,0.000000,0.064103
24,How can I subscribe to notifications?,You can subscribe to notifications from your a...,To subscribe to notifications (such as order u...,0.007712,0.086420,0.050000,0.074074
25,How do I unsubscribe from emails?,You can unsubscribe using the link at the bott...,"To unsubscribe from marketing emails, follow t...",0.001239,0.088000,0.016129,0.056000
26,What should I do if I forgot my username?,You can recover your username by contacting cu...,Here are the general steps to recover a forgot...,0.003822,0.109589,0.027778,0.082192
27,How do I verify my account?,You can verify your account by following the v...,"To verify your account, follow these general s...",0.005811,0.132353,0.059701,0.102941
28,Can I order multiple products together?,"Yes, you can add multiple products to your car...","Yes, you can order multiple products in a sing...",0.007058,0.100000,0.050505,0.090000
29,How do I apply for a warranty?,You can apply for warranty service by contacti...,SinceI don't have access to your specific comp...,0.002140,0.074074,0.014925,0.059259
30,How long is the warranty period?,The warranty period depends on the product and...,Warranty periods vary depending on the specifi...,0.005687,0.157895,0.089286,0.140351
31,Can I exchange my product?,You can request an exchange by submitting an e...,"Okay, the user is<unk><unk><unk><unk><unk><unk...",0.000000,0.000000,0.000000,0.000000
32,What happens if I receive a damaged product?,Contact customer support and provide details a...,"Ifyou receive a damaged product, here’s what t...",0.002796,0.073733,0.027907,0.064516
33,How do I update my phone number?,You can update your phone number from your Acc...,"Toupdate your phone number, follow these steps...",0.003940,0.139535,0.062992,0.093023
34,How do I check my shipping status?,You can check shipping status using your order...,You can typically check your shipping status u...,0.012580,0.140625,0.063492,0.140625
35,Can I save items for later?,You can save items by adding them to your wish...,"Yes, you can typically save items for later us...",0.007157,0.155844,0.053333,0.129870
36,How do I remove items from my cart?,You can remove items by opening your cart and ...,1. Open your shopping cart (usually via the ca...,0.009801,0.178571,0.090909,0.160714
37,Why did I receive the wrong item?,Contact customer support to report receiving t...,To help resolve the issue of receiving the wro...,0.007721,0.104478,0.045455,0.074627
38,How do I download my invoice?,You can download your invoice from the Orders ...,"To download your invoice, follow these steps:\...",0.004659,0.123894,0.054054,0.088496
39,Are there any shipping fees?,Shipping fees depend on your location and orde...,"Shipping fees can vary based on a few factors,...",0.003250,0.076433,0.012903,0.076433
40,How can I change my notification settings?,You can change notification settings from your...,Youcan adjust your notification preferences fr...,0.007605,0.109589,0.027778,0.068493
41,What if my package never arrives?,Contact customer support if your package does ...,"Ifyour package hasn't arrived, follow these st...",0.002167,0.105263,0.040000,0.092105
42,Can I pay using cash on delivery?,Cash on delivery is available in selected loca...,"Okay, the user is<unk><unk><unk><unk><unk><unk...",0.000000,0.005263,0.000000,0.005263
43,How do I apply for a refund?,Submit a refund request through your account o...,The service is busy right now. Please try agai...,0.015537,0.083333,0.000000,0.083333
44,How do I report a problem with my order?,You can report order problems by contacting cu...,The service is busy right now. Please try agai...,0.000000,0.000000,0.000000,0.000000
45,How do I know my personal data is safe?,We protect your personal data using security m...,The service is busy right now. Please try agai...,0.000000,0.000000,0.000000,0.000000
46,How can I update my billing information?,You can update billing information from the pa...,The service is busy right now. Please try agai...,0.000000,0.086957,0.000000,0.086957
47,How do I find a product?,You can search for products using the search b...,The service is busy right now. Please try agai...,0.000000,0.080000,0.000000,0.080000
48,How do I create a wishlist?,You can create a wishlist by clicking the Add ...,The service is busy right now. Please try agai...,0.015537,0.160000,0.000000,0.080000
49,How can I contact support about a technical is...,You can contact technical support through emai...,The service is busy right now. Please try agai...,0.000000,0.000000,0.000000,0.000000

In [47]:
import mlflow

In [48]:
mlflow.set_experiment("RAG Evaluation")

with mlflow.start_run():
    print("MLflow Run Started")

MLflow Run Started

In [ ]:
mlflow.log_param("embedding_model", "sentence-transformers/all-MiniLM-L6-v2")
mlflow.log_param("retrieval_k", 5)
mlflow.log_param("relevance_threshold", 0.25)

0.25

In [50]:
mlflow.log_metric("BLEU", sum(bleu_scores) / len(bleu_scores))
mlflow.log_metric("ROUGE-1", sum(rouge1) / len(rouge1))
mlflow.log_metric("ROUGE-2", sum(rouge2) / len(rouge2))
mlflow.log_metric("ROUGE-L", sum(rougeL) / len(rougeL))

In [ ]:
mlflow.end_run() 

print("Experiment Saved Successfully!")

Experiment Saved Successfully!